/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : CommentId,
  'text' : string,
  'author' : ProfileId,
  'timestamp' : bigint,
}
export type CommentId = bigint;
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : MessageId,
  'text' : string,
  'recipient' : ProfileId,
  'sender' : ProfileId,
  'timestamp' : bigint,
}
export type MessageId = bigint;
export type PostId = bigint;
export interface PostView {
  'id' : PostId,
  'author' : ProfileId,
  'likes' : Array<ProfileId>,
  'timestamp' : bigint,
  'caption' : string,
  'comments' : Array<CommentId>,
  'photo' : [] | [ExternalBlob],
}
export type ProfileId = Principal;
export interface UserProfileView {
  'id' : ProfileId,
  'displayName' : string,
  'friends' : Array<ProfileId>,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[PostId, string], CommentId>,
  'addFriend' : ActorMethod<[ProfileId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[string, [] | [ExternalBlob]], PostId>,
  'createProfile' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
  'getAllPostsSorted' : ActorMethod<[], Array<PostView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[PostId], Array<Comment>>,
  'getFeed' : ActorMethod<[], Array<PostView>>,
  'getFriends' : ActorMethod<[], Array<ProfileId>>,
  'getMessagesWith' : ActorMethod<[ProfileId], Array<Message>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'sendMessage' : ActorMethod<[ProfileId, string], MessageId>,
  'unlikePost' : ActorMethod<[PostId], undefined>,
  'updateProfile' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];